### ISSUE TITLE
Bitfinex supported symbols don't match the formatter

### ISSUE THREAD

**Issue by fieldfoxWim** [nlsdfnbch/bitex#106]
Hi 
I was looking for an exchange wrapper like this. Because of the lots of "BETA" states in the master I started with the DEV, and stumbled on this issue:

### Overview Description
Can 't get the ticker from Bitfinex, for pairs, because the formatting of the /symbols call does not match the formatter

# Steps to Reproduce

1. Create Bitfinex instance
2. Call ticker() for ETHBTC

# Actual Results
AssertionError: ETHBTC is not supported by this exchange!

# Expected Results
`b'{"mid":"0.0443075","bid":"0.044307","ask":"0.044308","last_price":"0.044308","low":"0.043911","high":"0.045001","volume":"57936.8276602","timestamp":"1511345627.1680584"}'`

# Reproducibility
Everytime

# Additional Information
DEV Branch

**Comment by nlsdfnbch** [comment]
Hey @fieldfoxWim,

thanks for contributing! How are you installing the project ? If you're installing using the repo using the `dev` branch, try the `pip install --pre bitex` and let me know if the issue is resolved. That's the current beta. If you're alread using that, could you show me your code?

Cheers,
Nils

**Comment by fieldfoxWim** [comment]
Hey Nils

I tested both:
- downloading the dev branch
- installing `pip install --pre bitex`

Both with the same exception

This is my code:

`from bitex import Bitfinex, HitBTC
from bitex.pairs import BTCUSD, ETHBTC, LTCBTC, ETHUSD

def main():
    b = Bitfinex(config="auth/bitfinex.ini")
    response = b.ticker(ETHBTC)
    print(response.content)

if __name__ == "__main__":
    main()`

**Comment by nlsdfnbch** [comment]
Curious. It may be that the pairs aren't pulled from bitfinex correctly, or that indeed the formatter is wrong. I'll have a look at this tomorrow morning and let you know!

**Comment by nlsdfnbch** [comment]
Source of the problem:
The symbols are pulled correctly, but the PairFormatter for bitfinex returns the pairs in Caps, while the symbols pulled via the Interface class are lower-case.
This is technically ok - both upper and lower case versions of pairs are accepted by the API, but the `check_pairs` decorator does not know this. so the bitfinex `format_for` call needs to be adjusted.
