### ISSUE TITLE
HitBtc Missing apikey parameter

### ISSUE THREAD

**Issue by Othosbro** [nlsdfnbch/bitex#114]
I try 
`hitbtc = HitBtc(key_file='./keys/hitbtc.key');
hitbtc.deposit_address('BTC').json()` but the response is
`{'code': 'InvalidContent', 'message': 'Missing apikey parameter'}`
api and secret keys installed properly.

**Comment by Othosbro** [comment]
Standard `pip` release. Just `pip3 install bitex`

**Comment by nlsdfnbch** [comment]
Please run your code with the log level set to `logging.DEBUG` and post the log (make sure to replace your key / secret before uploading).

```python
import logging
log_format = "%(asctime)s\t%(name)s\t%(levelname)s\t%(pathname)s:Line%(lineno)s:%(funcName)s\t%(message)s"
logging.basicConfig(level=logging.INFO, filename='bitex.log', filemode='w+', format=log_format)

# ... your code here

```

**Comment by Othosbro** [comment]
`DEBUG:bitex.api.REST.api:Making request to: http://api.hitbtc.com/api//1/trading/balance, kwargs: {'headers': {'Api-signature': 'cc657984210c323f6ab8a4c8ede97f4fd78379a964e6064c5432cb120b56f1fba9f900213f4d108a3019b420b4d9c2ad6742b5cf1e15ebf7ee2daaf32f7e1183'}, 'data': {}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): api.hitbtc.com
DEBUG:urllib3.connectionpool:http://api.hitbtc.com:80 "GET /api//1/trading/balance HTTP/1.1" 400 62
DEBUG:bitex.api.REST.api:Made GET request made to http://api.hitbtc.com/api//1/trading/balance, with headers {'User-Agent': 'python-requests/2.18.4', 'Api-signature': 'cc657984210c323f6ab8a4c8ede97f4fd78379a964e6064c5432cb120b56f1fba9f900213f4d108a3019b420b4d9c2ad6742b5cf1e15ebf7ee2daaf32f7e1183', 'Connection': 'keep-alive', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate'} and body None. Status code 400
ERROR:bitex.utils:return_api_response: HTTPError for url http://api.hitbtc.com/api//1/trading/balance
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitex/utils.py", line 40, in wrapper
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://api.hitbtc.com/api//1/trading/balance`

**Comment by nlsdfnbch** [comment]
Yup, that parameter is definitely missing. Patching it now, give me a few minutes.

**Comment by Othosbro** [comment]
The problem with poloniex  also exists.
I try `poloniex.balance().json()` and response is:
`{'error': 'Nonce must be greater than 3025292569069240. You provided 302529601757660.'}`
Fix it, please

**Comment by nlsdfnbch** [comment]
Is this a constantly happening issue? Or sporadically?

**Comment by Othosbro** [comment]
Constantly.  
`def nonce(self):
        """
        Creates a Nonce value for signature generation
        :return:
        """
        return str(round(100000 * time.time()) * 2)`
Change 2 to 20 and it works.
The problem with hitbtc apikey is not solved (

**Comment by Othosbro** [comment]
Here is example of hitbtc api request
https://gist.github.com/hitbtc-com/e265a49c38a86c610294

**Comment by nlsdfnbch** [comment]
I can't just increase the factor - there's similar issues for other exchanges, but that's not an error in code. It may work today, but perhaps next week I need to increase it again. the multiplication by `1000` was already one such fix. 

If you require the Nonce to be multiplied by a bigger factor, please modify this code yourself.

**Comment by Othosbro** [comment]
I modified `hitbtc.py` with respect to link above. Now I have another error:
'{'error': {'code': 1002, 'description': '', 'message': 'Authorization failed'}}'

DEBUG:bitex.api.REST.api:Making request to: http://api.hitbtc.com/api/1/trading/balance?apikey=c0e42c4f722dd5fcf5f93795754db073&nonce=3025298037383640, kwargs: {'data': {}, 'headers': {'Api-signature': 'c371286c28013f327bdca64cd98cebca5e6ab3699fe2950ab28436925359a051a8e5e2aed3c38bc6cd21763f4bf68feee93315f6facdea0b0'}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): api.hitbtc.com
DEBUG:urllib3.connectionpool:http://api.hitbtc.com:80 "GET /api/1/trading/balance?apikey=c0e42c4f722dd5fcf5f93795754db01233&nonce=3025298037383640 HTTP/1.1" 401 73

**Comment by nlsdfnbch** [comment]
If you're using the gist's code, this indicates that your API key doesn't have the required permissions. If that isn't the case, you'll have to take it up with hitbtc directly.

**Comment by Othosbro** [comment]
The problem is not solved.
`DEBUG:bitex.api.REST.api:Making request to: http://api.hitbtc.com/api//1/trading/balancenonce=302530441189250&apikey=7c36d31206a7b367dd7f1ed0e9e5fb66, kwargs: {'headers': {'Api-signature': '0c2035c35a94a563cedf8ba7c231cf6f2a72adf1c4aa0c9c226e26d434005ef8658e18af0d130bbda839d6f7bef413868de1b0bee7434e85f223e81250f6ccb4'}, 'data': {'nonce': '302530441189250', 'apikey': '7c36d31206a7b367dd7f1ed0e9e5fb66'}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): api.hitbtc.com
DEBUG:urllib3.connectionpool:http://api.hitbtc.com:80 "GET /api//1/trading/balancenonce=302530441189250&apikey=7c36d31206a7b367dd7f1ed0e9e5fb66 HTTP/1.1" 404 139
DEBUG:bitex.api.REST.api:Made GET request made to http://api.hitbtc.com/api//1/trading/balancenonce=302530441189250&apikey=7c36d31206a7b367dd7f1ed0e9e5fb66, with headers {'Connection': 'keep-alive', 'Api-signature': '0c2035c35a94a563cedf8ba7c231cf6f2a72adf1c4aa0c9c226e26d434005ef8658e18af0d130bbda839d6f7bef413868de1b0bee7434e85f223e81250f6ccb4', 'Content-Length': '61', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.18.4'} and body nonce=302530441189250&apikey=7c36d31206a7b367dd7f1ed0e9e5fb66. Status code 404
ERROR:bitex.utils:return_api_response: HTTPError for url http://api.hitbtc.com/api//1/trading/balancenonce=302530441189250&apikey=7c36d31206a7b367dd7f1ed0e9e5fb66
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitex/utils.py", line 40, in wrapper
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://api.hitbtc.com/api//1/trading/balancenonce=302530441189250&apikey=7c36d31206a7b367dd7f1ed0e9e5fb66`
