### ISSUE TITLE
HitBtc error

### ISSUE THREAD

**Issue by Othosbro** [nlsdfnbch/bitex#115]
>hitbtc.balance().json()

> DEBUG:bitex.api.REST.api:Making request to: http://api.hitbtc.com/api//1/trading/balancenonce=302530441189250&apikey=7c36d31206a7b367dd7f1ed0e9e5fb66, kwargs: {'headers': {'Api-signature': '0c2035c35a94a563cedf8ba7c231cf6f2a72adf1c4aa0c9c226e26d434005ef8658e18af0d130bbda839d6f7bef413868de1b0bee7434e85f223e81250f6ccb4'}, 'data': {'nonce': '302530441189250', 'apikey': '7c36d31206a7b367dd7f1ed0e9e5fb66'}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): api.hitbtc.com
DEBUG:urllib3.connectionpool:http://api.hitbtc.com:80 "GET /api//1/trading/balancenonce=302530441189250&apikey=7c36d31206a7b367dd7f1ed0e9e5fb66 HTTP/1.1" 404 139
DEBUG:bitex.api.REST.api:Made GET request made to http://api.hitbtc.com/api//1/trading/balancenonce=302530441189250&apikey=7c36d31206a7b367dd7f1ed0e9e5fb66, with headers {'Connection': 'keep-alive', 'Api-signature': '0c2035c35a94a563cedf8ba7c231cf6f2a72adf1c4aa0c9c226e26d434005ef8658e18af0d130bbda839d6f7bef413868de1b0bee7434e85f223e81250f6ccb4', 'Content-Length': '61', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.18.4'} and body nonce=302530441189250&apikey=7c36d31206a7b367dd7f1ed0e9e5fb66. Status code 404
ERROR:bitex.utils:return_api_response: HTTPError for url http://api.hitbtc.com/api//1/trading/balancenonce=302530441189250&apikey=7c36d31206a7b367dd7f1ed0e9e5fb66
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitex/utils.py", line 40, in wrapper
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://api.hitbtc.com/api//1/trading/balancenonce=302530441189250&apikey=7c36d31206a7b367dd7f1ed0e9e5fb66

**Comment by Othosbro** [comment]
No. Цhen you have time, please check the correctness of the code

**Comment by Othosbro** [comment]
According to https://bitcointalk.org/index.php?topic=706205.0
the signature must be generated only with /api/1/trading/balance?nonce=NONCE&apikey=APIKEY

But I still have `'message': 'Authorization failed'`

**Comment by nlsdfnbch** [comment]
I can't check the authenticated endpoints, as Im not registered with HitBTC. Your help is appreciated.

**Comment by Othosbro** [comment]
msg should look like `msg = '/api'+endpoint_path + "?"+'nonce='+nonce+'&apikey='+self.key`
but the error exists (`'message': 'Authorization failed'`)

**Comment by nlsdfnbch** [comment]
If you look here:
```
http://api.hitbtc.com/api//1/trading/balancenonce=302530441189250&apikey=7c36d31206a7b367dd7f1ed0e9e5fb66
```
You can see this is what I'm doing (except for the missing `?` after `balance`, which I fixes as I said above).
