### ISSUE TITLE
TypeError: Can't instantiate abstract class Bitfinex with abstract methods is_supported

### ISSUE THREAD

**Issue by ckrmml** [nlsdfnbch/bitex#116]
Been fiddling around with bitex, probably i'm just to stupid to get it right, but i get this error

```
Traceback (most recent call last):
  File "ticker.py", line 143, in <module>
    main()
  File "ticker.py", line 138, in main
    b = Bitfinex(config="auth/bitfinex.ini")
TypeError: Can't instantiate abstract class Bitfinex with abstract methods is_supported
```

with this code

```
from bitex import Bitfinex
from bitex.pairs import BTCUSD, ETHBTC, LTCBTC, ETHUSD

def main():
    b = Bitfinex(config="auth/bitfinex.ini")
    response = b.ticker(ETHBTC)
    print(response.content)

if __name__ == "__main__":
    main()
```

using latest dev-branch, pulled as zip from github

**Comment by ckrmml** [comment]
tried `pip install --pre bitex`, works now. Encountered #106 and added the fix by hand. works

**Comment by nlsdfnbch** [comment]
The above error stems from the fact that I haven't updated the interfaces yet - the base classes are now abstract base classes and need to implement all of its abstract methods. Since that isn't the case yet, you get the error. 

Thanks for trying out bitex!
