### ISSUE TITLE
Dev branch : Unnecessarily abstract methods

### ISSUE THREAD

**Issue by HughMacdonald** [nlsdfnbch/bitex#119]
Should Interface.is_supported() and Interface.request() be defined as abstract? Both have implementations in the abstract definition, and I've found that most (if not all) interfaces don't work because of is_supported() missing. Some (Cryptopia, for example) doesn't have either method defined, which should be fine.

**Comment by nlsdfnbch** [comment]
You're right. I guess I went a little overboard with the abstract decorator there! 😃
