### ISSUE TITLE
Dev branch : Accessing method_verb from sign_request_kwargs()

### ISSUE THREAD

**Issue by HughMacdonald** [nlsdfnbch/bitex#121]
In doing an implementation of the Binance interface, I've come across something that may well be a bug at their end, but one possible work-around would be to change `POST` and `DELETE` requests from putting the parameters in the query string to putting them in the request body.

However, `GET` requests require the parameters to be in the query string, so this would mean that `sign_request_kwargs()` would need to do something different depending on the method_verb.

The options are:

- Add method_verb as a parameter to be passed into `sign_request_kwargs()`, which would have to be implemented across the board.
- Override `private_query()` from `BinanceREST` and have it call different methods depending on the method_verb.

The second would be my preferred approach at the moment, but I wanted to give you the opportunity to consider both options and push me one way or the other if you had a preference.

Thanks

**Comment by nlsdfnbch** [comment]
The second option is definitely preferred- it's exchange specific, so let's make that implementation so as well.

**Comment by HughMacdonald** [comment]
That's what I went for in #122, so great.
