### ISSUE TITLE
Confusing at getting started

### ISSUE THREAD

**Issue by jvaldiviezo9** [nlsdfnbch/bitex#131]
Greets!

I'm writting because I don't know if there was significant changes beetween the 1.2.11 and 1.2.1 but I'm unable to understand how to get started with bitEx. Could you please guide me a little bit?

maybe an example with bittrex or bitfinex?  I installed all through pip using anaconda.

**Comment by jvaldiviezo9** [comment]
Greets!

I figure out how to run a simple program (was my fault at the beginning since I named my .py file with the same name of bitex). But now I'm experiencing some issues with a simple program:

from bitex import Bitfinex
c = Bitfinex(key,  secret)
print(c.balance())

it says this:

The API clients available in this package are deprecated and will be no longer available in their current form starting with version 2.0!
DEBUG:bitex.api.REST.api:Initialized API Client for URI: https://api.bitfinex.com; Will request on API version: v1
DEBUG:bitex.api.REST.api:Making request to: https://api.bitfinex.com/v1/balances, kwargs: {'headers': {'X-BFX-APIKEY': 'FYDgzImz1kQYerE1tlSWTfkTV1HWY8HQjBpbgZC8p4T', 'X-BFX-SIGNATURE': '376f8f2c942417a5ed227bfdb528d21ea365d7a0f6b1888a8c5376d310d14bc76cffe7a1cf6eb4058e7b71a71d216954', 'X-BFX-PAYLOAD': b'eyJyZXF1ZXN0IjogIi92MS9iYWxhbmNlcyIsICJub25jZSI6ICIzMDI3MjIxOTEzMTM2NTIifQ=='}}
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.bitfinex.com
DEBUG:requests.packages.urllib3.connectionpool:https://api.bitfinex.com:443 "POST /v1/balances HTTP/1.1" 200 None
<Response [200]>

what proceeds?

**Comment by nlsdfnbch** [comment]
All returned response by `bitex` are `requests.Response` objects. If you want to access the data of the response, then you need to call its `json()` method. Like so:

```
from bitex import Bitfinex
c = Bitfinex(key, secret)
response = c.balance()
print(response.json())
```
