### ISSUE TITLE
429 Response handling?

### ISSUE THREAD

**Issue by Jwely** [nlsdfnbch/bitex#144]
I was surprised to see the GDAX interface does not provide any handling for the submission of many requests that may exceed API limits. Is there any intention to add features in this category for GDAX or other interfaces in the future?

**Comment by nlsdfnbch** [comment]
Hey @Jwely,
There currently is no such feature planned. I believe that  rate-limiting is job of the user and not the library, as this may interfere with trading strategies in an unexpected way. 

Thanks for your question!

**Comment by Jwely** [comment]
Understood.

I've been using it for analyzing historical trades where waiting any arbitrary time for a response is no problem, but any live trade strategy will have non trivial requirements for handling this kind of thing.
