### ISSUE TITLE
HitBTC REST API url miscalculated

### ISSUE THREAD

**Issue by emestee** [nlsdfnbch/bitex#147]
The default value of `api_version` for HitBTCREST() is 1, which is prefixed to the request URLs; however the actual URLs begin with 'api', i.e. the request URL is calculated to be `https://api.hitbtc.com/1/public/symbols` instead of `https://api.hitbtc.com/api/1/public/symbols` 

A hacky solution is to initialize the client abusing the api_version prefix: 

`client = HitBTCREST(api_version='api/1')`

**Comment by nlsdfnbch** [comment]
Or update the api url to `https://api.hitbtc.com/api`, no ?
