### ISSUE TITLE
Add CI Testing using Travis

### ISSUE THREAD

**Issue by nlsdfnbch** [nlsdfnbch/bitex#80]
setup travis.yml to automate testing.

**Comment by Mukz95** [comment]
Hello, I have set up the travis build pipeline of my fork to automate tests with the yml configuration as a pull request. If you log into travis it should allow you to click the repo thus starting the worker builds 👍

**Comment by nlsdfnbch** [comment]
Purrs like a kitten. Fails like the deathstar, too. But that's ok. ;)
