### ISSUE TITLE
Spell check all the things!

### ISSUE THREAD

**Issue by nlsdfnbch** [nlsdfnbch/bitex#89]
There's likely a boat full of spelling errors and grammatical atrocities in the code - log messages, doc strings and comments all need to be reviewed. 

Feel free to contribute!

**Comment by nlsdfnbch** [comment]
@schamp , cool. cool cool cool.
One thing: make sure you do this on the release branch!
cheers,
Nils

**Comment by haripalbaluja** [comment]
Kindly review PR #90  on spell check.

**Comment by haripalbaluja** [comment]
I wanted to do this

**Comment by haripalbaluja** [comment]
I have opened a new PR #93 on branch realease-2.0.0. You could check it.
Regards
Haripal
